
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const RESET_ERROR_MESSAGE='RESET_ERROR_MESSAGE'
export const DELETE_TODO_SUCCESS='DELETE_TODO_SUCCESS'
export const POST_TODO_SUCCESS='POST_TODO_SUCCESS'
export const PATCH_TODO_SUCCESS='PATCH_TODO_SUCCESS'
export const LOAD_TODO_SUCCESS='LOAD_TODO_SUCCESS'
